### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by Kayoto1** [ECLaboratorio/BubbleShowCase-iOS#1]
Hey, first I must give you good excellent notice for this project (-;
I found that there is a bug while tyring to mark bubble on an element inside the cell. there is a gap between the original element and the bubble.

Thank you

**Comment by fermoya** [comment]
Hi Kayoto,

Thanks for the feedback, I really appreciate. I've seen you've closed the issue, could you please tell me if there was something wrong with it? If so, I'll give it a look ASAP.

Thank you so much.
